### ISSUE TITLE
在安卓11上运行调用滤镜api报错

### ISSUE THREAD

**Issue by bobo19870225** [HMS-Core/hms-image-vision-java#2]
--logversion:utracea
Process Name: 'com.godoperate.artistalbum'
Thread Name: 'main'
Back traces starts.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.godoperate.artistalbum/com.godoperate.artistalbum.ui.activity.OriginalGridActivity}: java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3733)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3891)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2298)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:8142)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
Caused by: java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
	at android.os.Parcel.createException(Parcel.java:2371)
	at android.os.Parcel.readException(Parcel.java:2354)
	at android.os.Parcel.readException(Parcel.java:2296)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8827)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3107)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3071)
	at com.huawei.hms.image.visionkit.utils.CommonUtility.getNetworkClass(Unknown Source:8)
	at com.huawei.hms.image.visionkit.ImageVisionApiService$IRemoteImageVisionApiImpl.saveContext(:2)
	at com.huawei.hms.image.visionkit.aidl.IRemoteLocalApi$Stub.onTransact(Unknown Source:239)
	at android.os.Binder.transact(Binder.java:1043)
	at com.huawei.hms.image.vision.E$a$a.c(:5)
	at com.huawei.hms.image.vision.ImageVisionImpl.b(:53)
	at com.huawei.hms.image.vision.ImageVisionImpl.setVisionCallBack(:4)
	at com.xiaopo.flying.puzzle.filter.HUAWEIFilter.init(HUAWEIFilter.java:40)
	at com.godoperate.artistalbum.ui.activity.OriginalGridActivity.initFilter(OriginalGridActivity.java:127)
	at com.godoperate.artistalbum.ui.activity.OriginalGridActivity.onCreate(OriginalGridActivity.java:121)
	at android.app.Activity.performCreate(Activity.java:8119)
	at android.app.Activity.performCreate(Activity.java:8103)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3706)
	... 11 more
Back traces ends.
按照提示申请了android.Manifest.permission.READ_PHONE_STATE权限，运行不报错，但无法获取渲染的图片

**Comment by bobo19870225** [comment]
更正：按照提示申请了android.Manifest.permission.READ_PHONE_STATE权限，可以正常工作
